spring.application.name=demo-park

# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# Driver e Conexão
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate (JPA)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SpringDoc OpenApi 3 & Swagger 3
# Isso a baixo indica em qual url vai rodar a documentação do swagger, no caso, http://localhost:8080/docs-park.html
springdoc.swagger-ui.path=/docs-park.html
# Isso a baixo indica abre o código gerado pela OpenApi
springdoc.api-docs.path=/api-park
# Isso a baixo serve para indicar qual pacote vai ser analisado pelo springdoc para gerar a documentação da API, no caso, o pacote onde estão os controllers
springdoc.packages-to-scan=com.api.demo_park.usuario.controller
